### ISSUE TITLE
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2)  and requested shape (3,2)

### ISSUE THREAD

**Issue by ghost** [vidursatija/BlazePalm#6]
Hi,

- Running `run_detector.py` program on Ubuntu 22.04.2 LTS.
- Pytorch version is 2.0.1+cpu

Initially, I received this [issue](https://github.com/vidursatija/BlazePalm/issues/2). I was able to fix that issue by following the solution mentioned in the issue.

Now, I am getting this error:
```
aravind@aravind-Latitude-E6420:ML$ python3 run_detector.py 
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/aravind/work/pp/machine_learning/BlazePalm/ML/run_detector.py", line 33, in <module>
    cropped_hand = np.pad(cropped_hand,
  File "<__array_function__ internals>", line 200, in pad
  File "/home/aravind/.local/lib/python3.10/site-packages/numpy/lib/arraypad.py", line 744, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/home/aravind/.local/lib/python3.10/site-packages/numpy/lib/arraypad.py", line 518, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 200, in broadcast_to
  File "/home/aravind/.local/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 413, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/aravind/.local/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 349, in _broadcast_to
    it = np.nditer(
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2)  and requested shape (3,2)
```

Please help.

Thank you,
Aravind.

**Comment by vidursatija** [comment]
Hi Aravind!
Can you try this
```python
frame = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
```
after line 18?

**Comment by ghost** [comment]
Hi @vidursatija ,

I added above statement after line 18. I am getting this error:
```
Traceback (most recent call last):
  File "/home/aravind/work/pp/machine_learning/BlazePalm/ML/run_detector.py", line 20, in <module>
    hh, ww, _ = frame.shape
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by Mayo001** [comment]
> Hi @vidursatija ,
> 
> I added above statement after line 18. I am getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/aravind/work/pp/machine_learning/BlazePalm/ML/run_detector.py", line 20, in <module>
>     hh, ww, _ = frame.shape
> ValueError: not enough values to unpack (expected 3, got 2)
> ```

Hi! I also encountered the same error, which was caused by the lack of a return statement in the forward() function.

**Comment by vidursatija** [comment]
please change it to `hh, ww = frame.shape`
